version: 2

jobs:
  build:
    working_directory: /go/src/github.com/marshallbrekka/protobuf-doctor
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            go test ./...
